# Generated by Django 4.0.4 on 2022-07-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='photo',
        ),
    ]
